### ISSUE TITLE
replace MaxAwarded with maxAwardedTotal AND maxAmount

### ISSUE THREAD

**Issue by KBorchar** [schul-cloud/gamification#27]
### Situation

Currently, maxAwarded is not time-sensitive, meaning an achievement A with maxAwarded: 1 can be awarded infinite times as long as it's replaced by another achievement B with replaces: A. 

### Proposal:
Two fields for achievements: 
- maxAwardedTotal (total number of times that achievement can be had by someone EVER, even if currently 0)
- maxAmount (number of times the achievement can be held AT ONCE)

**Comment by cmfcmf** [comment]
Done in #57.
