### ISSUE TITLE
How to get VoluntarySelfTestTakenAward?

### ISSUE THREAD

**Issue by catamaican** [schul-cloud/gamification#70]
In your demo data you have an achievement called "VoluntarySelfTestTakenAward".

What data (POST requests) should be made in order to obtain it? Where and how to pass "completion_percentage"?

Thank you

**Comment by cmfcmf** [comment]
Good question; here's the POST data to trigger this achievement:
```json
{
  "user_id": "Chris", 
  "name": "VoluntarySelfTestTaken", 
  "payload": {
    "completion_percentage": 100
  }
}
```
